name: Build macOS DMG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app
        pip install rumps
        pip install pydexcom
        pip install setuptools
        pip install pyobjc_framework_Cocoa
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Verify setup.py
      run: |
        python -m py_compile setup.py
        
    - name: Build application with py2app
      run: |
        python setup.py py2app
        
    - name: Create DMG
      run: |
        # Install create-dmg
        brew install create-dmg
        
        # Create DMG from the app bundle
        create-dmg \
          --volname "DexcomNavBarIcon" \
          --volicon "icon.icns" \
          --window-pos 200 120 \
          --window-size 600 400 \
          --icon-size 100 \
          --icon "DexcomNavBarIcon.app" 175 190 \
          --hide-extension "DexcomNavBarIcon.app" \
          --app-drop-link 425 190 \
          "DexcomNavBarIcon.dmg" \
          "dist/DexcomNavBarIcon.app"
    
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v3
      with:
        name: DexcomNavBarIcon-dmg
        path: DexcomNavBarIcon.dmg
